version: 2.1

orbs:
  kurtosis-docs-checker: kurtosis-tech/docs-checker@0.2.0

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-1604:202007-01
      # DO NOT USE THIS YET! This costs 200 credits *per job run* so is extremely expensive for the free plan, but we can turn it on one day if we get more credits
      # docker_layer_caching: true

# NOTE: Because CircleCI jobs run on separate machines from each other, we duplicate steps (like checkout) between jobs. This is because doing the "correct" DRY
#  refactoring of, "one job for checkout, one job for build Docker image, etc." would require a) persisting files between jobs and b) persisting Docker images between
#  jobs. Both are annoying (saving/loading workspaces require re-downloading the workspace over the network, and there doesn't seem to be a good way to do Docker
#  images), so we run everything inside a single job.
# See also: https://discuss.circleci.com/t/can-docker-images-be-preserved-between-jobs-in-a-workflow-without-a-manual-load-save/23388/12
jobs:
  check_code:
    executor: ubuntu_vm
    steps:
      - checkout
      - run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
      - run: bash .circleci/validate-all-bootstraps.sh "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" "${SIMULATED_TRIAL_USER_CLIENT_ID}" "${SIMULATED_TRIAL_USER_CLIENT_SECRET}"

workflows:
  build:
    jobs:
      # ============ Jobs that run upon PR submission ===============
      - kurtosis-docs-checker/check-docs:
          markdown-link-check-config-json: |
            {
                "replacementPatterns": [
                    {
                        "pattern": "^../kurtosis-core",
                        "replacement": "https://docs.kurtosistech.com/kurtosis-core"
                    },
                    {
                        "pattern": "^../kurtosis-client",
                        "replacement": "https://docs.kurtosistech.com/kurtosis-client"
                    }
                ]
            }
          filters:
            branches:
              ignore:
                - develop
                - master
      - check_code:
          context:
            - docker-user
            - simulated-trial-user
          filters:
            branches:
              ignore:
                - develop
                - master

      # ============== Jobs that run upon release ==================
      # None for now
